services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    profiles: [dev]
    env_file:
      - .env
    environment:
      - SECRET_KEY=${FLASK_SECRET_KEY}
      - DB_URL=${FLASK_DB_URL}
    ports:
      - "3001:3001"
    command: python3 run.py
  test:
    build:
      context: .
      dockerfile: Dockertest
    profiles: [test]
    env_file:
      - .env.test
    environment:
      - SECRET_KEY=${FLASK_SECRET_KEY}
      - DB_URL=${FLASK_DB_URL}
    ports:
      - "3002:3002"
    command: pytest
